version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: Dovpanda
    path: ""
    text-resources:
      - path: requirements.txt
        format: flat-key-value
