language: python
script: python -m unittest tests/tests.py
deploy:
  provider: pypi
  user: __token__
  password:
    secure: zcEmZ430JUqX2+dIKYRihNND1QqYsgtBVYxBmHowoYQ1zrJipGjN7HUimCqsRH21yFvFmpikgDp4jCk4kPgKrh9c0PnQk80rJmbXQVKmV1ADzKOtjwMUwsUDemAn+uFJmAZYXjXeimy8EIVkA11DVH8ShixYmPCtpx1MJVLWcpxpn2Mn++3w7KD0rM/fmnSm3q9JOTiR5tXb6iv9vK+ML6vU5vfQ3g7eR1CuQpnoijllrt3miUj0G2RjOI4uXvDX+tiSN/BGjSaDUpae5tqipTFuh7ZHA88SGoHYXwtKamqhzGRvFGTVCJERBjQk/ZtERHcuKd7MkBV5w9iILDre/YupsgGCORdLHX2iametP0gFwDATmRGkH3in3fbWAjgKn/jH9grBJMdxFsHj1OY9lOTDe3ui0sDCv8RWP9iQx4GvCADowBuNsNC2lwj7YL02RW+0+z/DHLB6jhSHYQ+8T+gXsaF4uYnVYPAKsdtP2qnSO61jHHx+UBr/WaJGZ08CWDKIkFYPrAA0vZB28UY6o2IYzIbx2vt4oF20L/sERoouhiqbZdLxGmshT5W5HWtP6fqUFjY/g809MjJfpLp90d1blunQJtUoXK2LgFW7DiRXPWKHzfdXa+0bAifr6shYxf9BUteBx1EZvF+0FwF62XCf5hdMAw90ryup/DjQDSg=
  distributions: sdist bdist_wheel
  on:
    tags: true
